version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04"
    user: root
    ports:
      - "1434:1433"
    volumes:
      - api-mssql:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Secret_Password123"
      ACCEPT_EULA: "Y"
volumes:
  api-mssql:

